# Generated by Django 2.0.4 on 2018-06-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'book',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=32, verbose_name='key')),
                ('value', models.CharField(db_column='value', max_length=32, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Config',
                'verbose_name_plural': 'Configs',
                'db_table': 'config',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MainModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=32, verbose_name='title')),
                ('subtitle', models.CharField(db_column='subtitle', max_length=128, verbose_name='subtitle')),
            ],
            options={
                'verbose_name': 'Main',
                'verbose_name_plural': 'MainItems',
                'db_table': 'main',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='name')),
                ('age', models.IntegerField(blank=True, db_column='age', default=0, null=True, verbose_name='age')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prop1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=32, verbose_name='key')),
                ('value', models.CharField(db_column='value', max_length=32, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Prop1',
                'verbose_name_plural': 'Prop1',
                'db_table': 'prop1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prop2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_column='key', max_length=32, verbose_name='key')),
                ('value', models.CharField(db_column='value', max_length=32, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Prop2',
                'verbose_name_plural': 'Prop2',
                'db_table': 'prop2',
                'managed': True,
            },
        ),
    ]
